# Dockerfile.dev - For development only!
FROM rust:1.89-bullseye

# Install pkgx for all the dev tools
RUN cargo install pkgx
RUN rustup component add clippy

# Set work dir
WORKDIR /app

# Make config directory
RUN mkdir -p /root/.config/pkg/.bridges/bridge

# Start nushell sesstion
CMD ["pkgx", "+nushell.sh", "nu@0.107.0"]
