# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  dev-build:
    desc: Build the dev docker container
    cmds: 
      - docker build -t pkg:latest -f Dockerfile.dev .

  dev:
    desc: Run the dev docker container
    cmds:
      - >-
        docker run -it --rm
        -v $PWD/src:/app/src
        -v $PWD/Cargo.toml:/app/Cargo.toml
        -v $PWD/Cargo.lock:/app/Cargo.lock
        -v $PWD/docs:/app/docs
        -v $PWD/examples/docker:/root/.config/pkg
        pkg:latest

  run:
    desc: Run the app
    cmds:
      - cargo run

  build:
    desc: Build the app
    cmds:
      - cargo build --release

  test:
    desc: Test the app
    cmds:
      - cargo test

  clean:
    desc: Clean the tmps and builds
    cmds:
      - cargo clean

  fmt:
    desc: Foramt the source code
    cmds:
      - cargo fmt
